apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jquarkus
  janus-idp.io/tekton: jquarkus
  backstage.io/kubernetes-id: jquarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jquarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
