apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jquarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jquarkus 
  name: jquarkus
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jquarkus
    weight: 100 
